baseURL: "https://yifan-zhang-in.github.io/hugo-website-main/" 
title: Yifan Zhang
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 
        - name: Newsletter
          url: https://pmichaillat.substack.com
          weight: 4

params:
    description: "I am a Professor of Subject at the University of Place. My research covers various topics.
consequat."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yifan Zhang
          subtitle: "I am a DPhil (PhD) candidate in Economics at the University of Oxford, funded by the Departmental Doctoral Bursary and the David Walton Distinguished Doctoral Scholarship. 
          My research interests span macroeconomics and macrofinance, with a specific focus on expectation formation and bounded rationality."
          imageUrl: "picture (1).jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Prof. Name
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Newsletter
              url: https://pmichaillat.substack.com
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:pascal.michaillat@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Prof. Name"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
